apiVersion: v1
kind: Secret
metadata:
  name: postgredb-secret
  namespace: rhbk
type: Opaque
stringData:
  db-user: keycloak
  db-password: Senha123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgredb-pvc
  namespace: rhbk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgredb
  namespace: rhbk
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgredb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgredb
  namespace: rhbk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgredb
  template:
    metadata:
      labels:
        app: postgredb
    spec:
      containers:
        - name: postgredb
          image: registry.redhat.io/rhel8/postgresql-13:latest
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgredb-secret
                  key: db-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgredb-secret
                  key: db-password
            - name: POSTGRESQL_DATABASE
              value: keycloakdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgredb-storage
      volumes:
        - name: postgredb-storage
          persistentVolumeClaim:
            claimName: postgredb-pvc  
