apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: keycloak-realm-apps 
  labels:
    app: sso
  namespace: rhbk
spec:
  keycloakCRName: keycloak 
  realm:
    id: apps
    realm: apps
    displayName: Realm para Aplicativos
    enabled: true
    registrationAllowed: false
    loginWithEmailAllowed: false
    verifyEmail: false 
    accessTokenLifespan: 300 
    ssoSessionIdleTimeout: 1800 
    ssoSessionMaxLifespan: 3600 
    roles:
      realm:
        - name: insertcard-service 
          description: Permissões para o serviço
    clients:
      - clientId: spring-artemis-producer-client
        protocol: openid-connect
        publicClient: false 
        bearerOnly: false
        standardFlowEnabled: false
        implicitFlowEnabled: false 
        directAccessGrantsEnabled: false 
        serviceAccountsEnabled: true
        redirectUris: [] 
        webOrigins: []   
        serviceAccountRoles:
          realm:
            - insertcard-service
